/*
 * Copyright (C) 2023-2024 The java-keyserver project team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.bmarwell.keyserver.application.port.repository;

import java.time.OffsetDateTime;

/// Secondary (outbound) port for the verification queue.
///
/// The application core enqueues one entry per PGP UID that has an email
/// address and needs ownership confirmation.  The adapter persists the entry
/// and returns the generated TSID so the handler can construct the verification
/// URI for logging (and later, emailing).
public interface VerificationQueueRepository {

    /// Data needed to create one verification queue entry.
    ///
    /// The `id` is generated by the adapter (via the node-aware TSID factory)
    /// and returned from {@link #enqueue}.
    record VerificationRequest(
            String fingerprint, String uidRaw, String uidEmail, String armoredKey, OffsetDateTime expiresAt) {}

    /// Persists a single verification queue entry and returns its TSID.
    ///
    /// @param request the data for this queue entry
    /// @return the TSID (`BIGINT`) assigned to the new row
    long enqueue(VerificationRequest request);
}
