-- The id column is a TSID stored as BIGINT, generated by the application layer.
-- TSID encodes a timestamp + node + sequence, so it is naturally time-sorted
-- and fits in a BIGINT without the index-fragmentation problems of UUID.
CREATE TABLE verification_queue
(
    id          BIGINT                   NOT NULL PRIMARY KEY,
    fingerprint TEXT                     NOT NULL,
    uid_raw     TEXT                     NOT NULL,
    uid_email   TEXT                     NOT NULL,
    armored_key TEXT                     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    state       TEXT                     NOT NULL DEFAULT 'PENDING',
    CONSTRAINT verification_queue_state_check
        CHECK (state IN ('PENDING', 'VERIFIED', 'EXPIRED', 'REJECTED'))
);

CREATE INDEX vq_fingerprint ON verification_queue (fingerprint);
CREATE INDEX vq_uid_email   ON verification_queue (uid_email);
CREATE INDEX vq_state       ON verification_queue (state);
CREATE INDEX vq_expires_at  ON verification_queue (expires_at);
